// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type AuthPayload struct {
	User   *User      `json:"user"`
	Tokens *TokenPair `json:"tokens"`
}

type Chat struct {
	ID            string `json:"id"`
	RequestID     string `json:"requestId"`
	CreatorID     string `json:"creatorId"`
	InitiatorID   string `json:"initiatorId"`
	CreatedAt     Time   `json:"createdAt"`
	LastMessageAt *Time  `json:"lastMessageAt,omitempty"`
}

type ChatMessage struct {
	ID        string  `json:"id"`
	ChatID    string  `json:"chatId"`
	SenderID  string  `json:"senderId"`
	Text      *string `json:"text,omitempty"`
	Photo     *string `json:"photo,omitempty"`
	CreatedAt Time    `json:"createdAt"`
	ReadAt    *Time   `json:"readAt,omitempty"`
}

type CreateRequestInput struct {
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Address     *string `json:"address,omitempty"`
}

type JobRequest struct {
	ID          string   `json:"id"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Address     *string  `json:"address,omitempty"`
	CreatedAt   Time     `json:"createdAt"`
	Photos      []*Photo `json:"photos"`
}

type LoginInput struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
}

type Mutation struct {
}

type Photo struct {
	ID        string `json:"id"`
	Path      string `json:"path"`
	CreatedAt Time   `json:"createdAt"`
}

type Profile struct {
	ID       string   `json:"id"`
	FullName string   `json:"fullName"`
	About    *string  `json:"about,omitempty"`
	City     *string  `json:"city,omitempty"`
	Skills   []string `json:"skills"`
}

type ProfileInput struct {
	FullName string   `json:"fullName"`
	About    *string  `json:"about,omitempty"`
	City     *string  `json:"city,omitempty"`
	Skills   []string `json:"skills,omitempty"`
}

type Query struct {
}

type RegisterInput struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
}

type SendMessageInput struct {
	ChatID string          `json:"chatId"`
	Text   *string         `json:"text,omitempty"`
	File   *graphql.Upload `json:"file,omitempty"`
}

type Subscription struct {
}

type TokenPair struct {
	AccessToken      string `json:"accessToken"`
	RefreshToken     string `json:"refreshToken"`
	AccessExpiresAt  Time   `json:"accessExpiresAt"`
	RefreshExpiresAt Time   `json:"refreshExpiresAt"`
}

type UploadPhotosInput struct {
	RequestID string            `json:"requestId"`
	Files     []*graphql.Upload `json:"files"`
}

type User struct {
	ID      string   `json:"id"`
	Phone   string   `json:"phone"`
	Profile *Profile `json:"profile,omitempty"`
}
