// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/99designs/gqlgen/graphql"
)

type AuthPayload struct {
	User   *User      `json:"user"`
	Tokens *TokenPair `json:"tokens"`
}

type Chat struct {
	ID            string `json:"id"`
	RequestID     string `json:"requestId"`
	CreatorID     string `json:"creatorId"`
	InitiatorID   string `json:"initiatorId"`
	CreatedAt     Time   `json:"createdAt"`
	LastMessageAt *Time  `json:"lastMessageAt,omitempty"`
}

type ChatMessage struct {
	ID        string  `json:"id"`
	ChatID    string  `json:"chatId"`
	SenderID  string  `json:"senderId"`
	Text      *string `json:"text,omitempty"`
	Photo     *string `json:"photo,omitempty"`
	CreatedAt Time    `json:"createdAt"`
	ReadAt    *Time   `json:"readAt,omitempty"`
}

type CreateRequestInput struct {
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Address     *string `json:"address,omitempty"`
}

type JobRequest struct {
	ID          string   `json:"id"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Address     *string  `json:"address,omitempty"`
	CreatedAt   Time     `json:"createdAt"`
	Photos      []*Photo `json:"photos"`
}

type LoginInput struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
}

type Mutation struct {
}

type Photo struct {
	ID        string `json:"id"`
	Path      string `json:"path"`
	CreatedAt Time   `json:"createdAt"`
}

type Profile struct {
	ID       string   `json:"id"`
	FullName string   `json:"fullName"`
	About    *string  `json:"about,omitempty"`
	City     *string  `json:"city,omitempty"`
	Skills   []string `json:"skills"`
}

type ProfileInput struct {
	FullName string   `json:"fullName"`
	About    *string  `json:"about,omitempty"`
	City     *string  `json:"city,omitempty"`
	Skills   []string `json:"skills,omitempty"`
}

type Query struct {
}

type RegisterInput struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
}

type SendMessageInput struct {
	ChatID string          `json:"chatId"`
	Text   *string         `json:"text,omitempty"`
	File   *graphql.Upload `json:"file,omitempty"`
}

type Subscription struct {
}

type TokenPair struct {
	AccessToken      string `json:"accessToken"`
	RefreshToken     string `json:"refreshToken"`
	AccessExpiresAt  Time   `json:"accessExpiresAt"`
	RefreshExpiresAt Time   `json:"refreshExpiresAt"`
}

type UploadPhotosInput struct {
	RequestID string            `json:"requestId"`
	Files     []*graphql.Upload `json:"files"`
}

type User struct {
	ID      string   `json:"id"`
	Phone   string   `json:"phone"`
	Roles   []Role   `json:"roles"`
	Profile *Profile `json:"profile,omitempty"`
}

type Role string

const (
	RoleCustomer Role = "CUSTOMER"
	RoleWorker   Role = "WORKER"
)

var AllRole = []Role{
	RoleCustomer,
	RoleWorker,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleCustomer, RoleWorker:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
